name: book_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture & State Management
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0       # Service Locator (DI)
  injectable: ^2.3.2   # Генерация DI
  equatable: ^2.0.5    # Сравнение объектов

  # Network & Backend
  supabase_flutter: ^2.3.0 # Официальный клиент
  
  # Data Classes & JSON
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI & Utilities
  intl: ^0.19.0        # Форматирование дат
  table_calendar: ^3.1.0 # Топовый календарь
  go_router: ^13.0.0   # Навигация (удобно для Deep Links)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1


flutter:
  uses-material-design: true

